imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
imagePullSecrets: ""
    
secretEnv:
  uniPass: "QzFHMmIzdTQjIw=="
  PERSISTENCEDBAPASSWORD:
     - schema: 1
       PASSWORD: "cGluREI5OSMjCg=="
db:
  brm:
    hostName: "dbvm.sub3b8b1321d.cluster1.oraclevcn.com"
    port: "1521"
    sid: "PINPDB"
    service: "PINPDB.sub3b8b1321d.cluster1.oraclevcn.com"
    userName: "pin"
    jdbcUrl: "jdbc:oracle:thin:@dbvm.sub3b8b1321d.cluster1.oraclevcn.com:1521/PINPDB.sub3b8b1321d.cluster1.oraclevcn.com"
  ece:
    hostName: "dbvm.sub3b8b1321d.cluster1.oraclevcn.com"
    port: "1521"
    sid: "PINPDB"
    service: "PINPDB.sub3b8b1321d.cluster1.oraclevcn.com"
    userName: "ece"
    jdbcUrl: "jdbc:oracle:thin:@dbvm.sub3b8b1321d.cluster1.oraclevcn.com:1521/PINPDB.sub3b8b1321d.cluster1.oraclevcn.com"
migration:
  pricingUpdater:
    hostName: "pdc-service"
    port: "8001"
    userName: "weblogic"
    connectionURL: "t3://pdc-service:8001"
storageClass:
  name: "rook-cephfs"

charging:
    kafkaConfigurations:
      kafkaConfigurationList:
         - name: "BRM"
           hostname: "ece-kafka:9093"
           topicName: "ECENotifications"
           suspenseTopicName: "ECESuspenseQueue"
           failureTopicName: "ecefailurequeue"
           overageTopicName: "eceoveragetopic"
           partitions: "200"
           failurePartitions: "200"
           externalTopicEnabled: "false"
           externalTopicName: "EceExtNotifications"
           externalPartitions: "15"
           walletLocation: "/home/charging/wallet/ecewallet/"
           kafkaProducerReconnectionInterval: "2000"
           kafkaProducerReconnectionMax: "30000"
           kafkaDGWReconnectionInterval: "2000"
           kafkaDGWReconnectionMax: "30000"
           kafkaBRMReconnectionInterval: "2000"
           kafkaBRMReconnectionMax: "30000"
           kafkaHTTPReconnectionInterval: "2000"
           kafkaHTTPReconnectionMax: "30000"
           persistFailedRequestsToKafkaTopic: "false"
           kafkaCDRTopicName: "ChfChargingRecords"
           kafkaCDRPartitions: "1"
           kafkaSSLEnabled: "false"
           kafkaTrustStoreLocation: ""
           kafkaCDRCompressionType: "gzip"

sslconnectioncertificates:
  SSLENABLED: "false"

emgateway:
   serviceFqdn: "ece-emg"
   emGatewayList:
      - coherenceMemberName: "emgateway1"
        jmxport: ""
        replicas: 1
        jmxEnabled: true
        coherencePort:
        jvmGCOpts: "-XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintAdaptiveSizePolicy -XX:-UseGCLogFileRotation -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:GCPauseIntervalMillis=200 -XX:NumberOfGCLogFiles=99"
        jvmJMXOpts: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false "
        jvmCoherenceOpts: "-Dpof.config=charging-pof-config.xml -Dcoherence.override=charging-coherence-override-dev.xml  -Dcoherence.security=false -Dsecure.access.name=admin"
        jvmOpts: "-Dece.metrics.http.service.enabled=true"
        restartCount: "0"
        emGatewayConfiguration:
           name: "emgateway1"
           port: "15502"
           threadPoolSize: "10"
           sslEnabled: "0"
           socketKeepAlive: "1"
           wallet: "/home/charging/wallet/brmwallet/server/cwallet.sso"
           clientAuthenticationEnabled: "0"
           updateResponseTimeout: "30000"

      - coherenceMemberName: "emgateway2"
        jmxport: ""
        replicas: 1
        jmxEnabled: true
        coherencePort:
        jvmGCOpts: "-XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintAdaptiveSizePolicy -XX:-UseGCLogFileRotation -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:GCPauseIntervalMillis=200 -XX:NumberOfGCLogFiles=99"
        jvmJMXOpts: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false "
        jvmCoherenceOpts: "-Dpof.config=charging-pof-config.xml -Dcoherence.override=charging-coherence-override-dev.xml  -Dcoherence.security=false -Dsecure.access.name=admin"
        jvmOpts: "-Dece.metrics.http.service.enabled=true"
        restartCount: "0"
        emGatewayConfiguration:
           name: "emgateway2"
           port: "15502"
           threadPoolSize: "10"
           sslEnabled: "0"
           socketKeepAlive: "1"
           wallet: "/home/charging/wallet/brmwallet/server/cwallet.sso"
           clientAuthenticationEnabled: "0"
           updateResponseTimeout: "30000"

charging:
   connectionConfigurations:
         BRMConnectionConfiguration:
            name: "brmConnection"
            hostName: "cm"
            protocol: "pcp"
            loginName: "root.0.0.0.1"
            cmPort: "11960"
            loginType: "1"
            numberOfConnections: "10"
            sslEnabled: "0"
            failOverConnectionUrls: ""
            eceWalletLocation: "/home/charging/wallet/ecewallet/"
            brmwallet: "/home/charging/wallet/brmwallet/client/cwallet.sso"


