imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
imagePullSecrets: ""
    
secretEnv:
  uniPass: "QzFHMmIzdTQjIw=="
  PERSISTENCEDBAPASSWORD:
     - schema: 1
       PASSWORD: "cGluREI5OSMjCg=="
db:
  brm:
    hostName: "dbvm.sub3b8b1321d.cluster1.oraclevcn.com"
    port: "1521"
    sid: "PINPDB"
    service: "PINPDB.sub3b8b1321d.cluster1.oraclevcn.com"
    userName: "pin"
    jdbcUrl: "jdbc:oracle:thin:@dbvm.sub3b8b1321d.cluster1.oraclevcn.com:1521/PINPDB.sub3b8b1321d.cluster1.oraclevcn.com"
  ece:
    hostName: "dbvm.sub3b8b1321d.cluster1.oraclevcn.com"
    port: "1521"
    sid: "PINPDB"
    service: "PINPDB.sub3b8b1321d.cluster1.oraclevcn.com"
    userName: "ece"
    jdbcUrl: "jdbc:oracle:thin:@dbvm.sub3b8b1321d.cluster1.oraclevcn.com:1521/PINPDB.sub3b8b1321d.cluster1.oraclevcn.com"
migration:
  pricingUpdater:
    hostName: "pdc-service"
    port: "8001"
    userName: "weblogic"
    connectionURL: "t3://pdc-service:8001"
storageClass:
  name: "rook-cephfs"

charging:
    kafkaConfigurations:
      kafkaConfigurationList:
         - name: "BRM"
           hostname: "ece-kafka:9093"
           topicName: "ECENotifications"
           suspenseTopicName: "ECESuspenseQueue"
           failureTopicName: "ecefailurequeue"
           overageTopicName: "eceoveragetopic"
           partitions: "200"
           failurePartitions: "200"
           externalTopicEnabled: "false"
           externalTopicName: "EceExtNotifications"
           externalPartitions: "15"
           walletLocation: "/home/charging/wallet/ecewallet/"
           kafkaProducerReconnectionInterval: "2000"
           kafkaProducerReconnectionMax: "30000"
           kafkaDGWReconnectionInterval: "2000"
           kafkaDGWReconnectionMax: "30000"
           kafkaBRMReconnectionInterval: "2000"
           kafkaBRMReconnectionMax: "30000"
           kafkaHTTPReconnectionInterval: "2000"
           kafkaHTTPReconnectionMax: "30000"
           persistFailedRequestsToKafkaTopic: "false"
           kafkaCDRTopicName: "ChfChargingRecords"
           kafkaCDRPartitions: "1"
           kafkaSSLEnabled: "false"
           kafkaTrustStoreLocation: ""
           kafkaCDRCompressionType: "gzip"

