imageRepository: "iad.ocir.io/id6cgo1s3kqm/brmcn15/"
imagePullSecrets: 
    - name: "oracle-registry"
    - name: "brm-registry"

uniPass: "QzFHMmIzdTQjIw=="
db:
    host: dbvm.sub3b8b1321d.cluster1.oraclevcn.com
    serviceName: PINPDB.sub3b8b1321d.cluster1.oraclevcn.com
    password: cGluREI5OSMjCg==
    sslMode: 'NO'

ocbrm:
    EnableSecurityContext: true
    storage_class:
        name: rook-cephfs
        create: false
ocbc:
    bc:
        configEnv:
            isOPSS: false
            ldapSkip: true
        pod:
            addOnPodSpec:
               securityContext:
                  runAsUser: 1000
                  runAsGroup: 3000
                  fsGroup: 2000
    bcws:
        configEnv:
            isOPSS: false
            ldapSkip: true
        pod:
            addOnPodSpec:
               securityContext:
                  runAsUser: 1000
                  runAsGroup: 3000
                  fsGroup: 2000

ocboc:
    boc:
        isEnabled: false

ocpdc:
     configEnv:
         rcuPrefix: rcupdc
         crossRefSchemaUserName: "pdcxref"
         pdcSchemaUserName: "pdc"
         pdcAdminUser: pdcuser
     enableSecurityContext: "true"
     secretValue:
        rcuWalletSchemaPassword: cGluREI5OSMjCg==
