imageRepository: "iad.ocir.io/idqji4proemh/brmcn-ps7/"
imagePullSecrets: "brm-registry"
uniPass: "QzFHMmIzdTQjIw=="

db:
    host: dbvm.sub73a9c38a7.cluster1.oraclevcn.com
    serviceName: PINPDB.sub73a9c38a7.cluster1.oraclevcn.com
    password: cGluREI5OSMjCg==
    sslMode: 'NO'


ocbrm:
    storage_class:
        name: rook-cephfs

ocboc:
    boc:
        isEnabled: false    # enable_boc

ocbc:
    bc:
        configEnv:
            isOPSS: false
            ldapSkip: true
    bcws:
        isEnabled: true    # enable_bcws
        configEnv:
            isOPSS: false
            ldapSkip: true

ocpdc:
     configEnv:
         rcuPrefix: rcupdc
