imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
imagePullSecrets: 
    - name: "brm-registry"

uniPass: "QzFHMmIzdTQjIw=="
db:
    host: dbvm.sub3b8b1321d.cluster1.oraclevcn.com
    serviceName: PINPDB.sub3b8b1321d.cluster1.oraclevcn.com
    password: cGluREI5OSMjCg==
    sslMode: 'NO'
ocbrm:
    pdc_deployed: true
    storage_class:
        create: false
        name: rook-cephfs
ocbc:
    bc:
        configEnv:
            isOPSS: false
            ldapSkip: true
        deployment:
            fmw:
                imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
                imageName: "middleware/fmw-infrastructure_cpu"
                imageTag: ":12.2.1.4-jdk8-ol8"
    bcws:
        configEnv:
            isOPSS: false
            ldapSkip: true
        deployment:
            fmw:
                imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
                imageName: "middleware/fmw-infrastructure_cpu"
                imageTag: ":12.2.1.4-jdk8-ol8"

ocboc:
    boc:
        isEnabled: false
        deployment:
            fmw:
                imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
                imageName: "middleware/fmw-infrastructure_cpu"
                imageTag: ":12.2.1.4-jdk8-ol8"


ocpdc:
     configEnv:
         rcuPrefix: rcupdc
         crossRefSchemaUserName: "pdcxref"
         pdcSchemaUserName: "pdc"
         pdcAdminUser: pdcuser
     deployment:
        fmw:
          imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
          imageName: "middleware/fmw-infrastructure_cpu"
          imageTag: ":12.2.1.4-jdk8-ol8"
         
