FROM iad.ocir.io/id6cgo1s3kqm/enablement/brm15/cm:15.0.0.0.0

USER root
COPY lib/fm_cust_pol_custom.so /oms/lib/fm_cust_pol_custom.so
RUN chown -R omsuser:root /oms/lib/fm_cust_pol_custom.so
RUN chmod 755 /oms/lib/fm_cust_pol_custom.so
USER omsuser
