# Copyright (c) 2020 Oracle Corporation and/or its affiliates. All rights reserved.
imageRepository: "iad.ocir.io/idqji4proemh/brmcn-ps7/"
imagePullSecrets: "brm-registry"

ocbrm:
    brm_root_pass: "QzFHMmIzdTQjIw=="
    wallet:
        client: "QzFHMmIzdTQjIw=="
        server: "QzFHMmIzdTQjIw=="
        root: "QzFHMmIzdTQjIw=="
    db:
        host: dbvm.sub73a9c38a7.cluster1.oraclevcn.com 
        port: 1521
        service: PINPDB.sub73a9c38a7.cluster1.oraclevcn.com 
        enable_partition: 'No'
        schemauser: pin
        schemapass: QzFHMmIzdTQjIw==
        schematablespace: pin00
        indextablespace: pinx00
db:
    sslMode: 'NO'
