# Copyright (c) 2020 Oracle Corporation and/or its affiliates. All rights reserved.
imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
imagePullSecrets:
    - name: "brm-registry"

uniPass: "QzFHMmIzdTQjIw=="

ocbrm:
    pdc_deployed: true
    brm_root_pass: "QzFHMmIzdTQjIw=="
    wallet:
        client: "QzFHMmIzdTQjIw=="
        server: "QzFHMmIzdTQjIw=="
        root: "QzFHMmIzdTQjIw=="
    db:
        host: dbvm.sub3b8b1321d.cluster1.oraclevcn.com 
        port: 1521
        service: PINPDB.sub3b8b1321d.cluster1.oraclevcn.com 
        enable_partition: 'No'
        schemauser: pin
        schemapass: QzFHMmIzdTQjIw==
        schematablespace: pin00
        indextablespace: pinx00
db:
    sslMode: 'NO'
