ocpdc:
    configEnv:
        importExport:
            IE_Operation: import
            IE_Component: config
            IE_File_OR_Dir_Name: Config_BRM15.xml
            extraCmdLineArgs: "-ow -ignoreID"
