imageRepository: "iad.ocir.io/id6cgo1s3kqm/brmcn15/"
imagePullSecrets: 
    - name: "oracle-registry"
    - name: "brm-registry"

uniPass: "QzFHMmIzdTQjIw=="

db:    
    host: dbvm.sub3b8b1321d.cluster1.oraclevcn.com
    serviceName: PINPDB.sub3b8b1321d.cluster1.oraclevcn.com
    user: sys
    password: cGluREI5OSMjCg==
    sslMode: "NO"

ocbrm:
    ece_deployed: true
    pdc_deployed: true
    EnableSecurityContext: true
    db:
        schemauser: pin
        schemapass: QzFHMmIzdTQjIw==
        schematablespace: pin00
        indextablespace: pinx00
        pipelineschemauser: pin
    cm:
        deployment:
            enable_publish: 1
    storage_class:
        create: false
        name: rook-cephfs
    virtual_time:
        enabled: true
    batchpipe:
        isEnabled: false

ocpdc:
     configEnv:
         rcuPrefix: rcupdc
         pdcSchemaUserName: pdc
         crossRefSchemaUserName: xref
         pdcAdminUser: pdcuser
     service:
         type: "ClusterIP"
     enableSecurityContext: "true"

ocpdcrsm:
    isEnabled: false
ocbc:
    bc:
        isEnabled: true
        configEnv:
            isOPSS: false
            isLDAPEnabled: false
        serverPod:
            podSecurityContext:
               runAsUser: 1000
               runAsGroup: 3000
               fsGroup: 2000
    bcws:
        isEnabled: true
        configEnv:
            isOPSS: false
            isLDAPEnabled: false
        serverPod:
            podSecurityContext:
               runAsUser: 1000
               runAsGroup: 3000
               fsGroup: 2000
ocboc:
    boc:
        isEnabled: false
ocpcc:
    pcc:
        isEnabled: false
ocrsm:
    rsm:
        isEnabled: false 

logging:
    isEnabled: false 

