# Copyright (c) 2021 Oracle Corporation and/or its affiliates. All rights reserved.
imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
imagePullSecrets: ""
uniPass: "QzFHMmIzdTQjIw=="

db:    
    host: dbvm.sub3b8b1321d.cluster1.oraclevcn.com
    port: 1521
    user: sys
    password: cGluREI5OSMjCg==
    serviceName: PINPDB.sub3b8b1321d.cluster1.oraclevcn.com
    role: sysdba
    sslMode: "NO"
ocbrm:
    pdc_deployed: true
    db:
        schemauser: pin
        schemapass: QzFHMmIzdTQjIw==
        schematablespace: pin00
        indextablespace: pinx00
        pipelineschemauser: pin
    cm:
        deployment:
            enable_publish: 1
    eai_js:
        deployment:
            eaiConfigFile: payloadconfig_ece_sync.xml
    storage_class:
        create: false
        name: rook-cephfs
    virtual_time:
        enabled: true
    batchpipe:
        isEnabled: false

ocpdc:
     configEnv:
         rcuPrefix: rcupdc
         pdcSchemaUserName: pdc
         crossRefSchemaUserName: xref
         pdcAdminUser: pdcuser
         transformation:
             supportECE: true
             isClearBRMSeedData: true 
             upgrade: false
         syncPDC:
             upgradeFromPS2: false
     service:
         type: "ClusterIP"
     wop:
         deployment: 
            fmw:
                imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
                imageName: "middleware/fmw-infrastructure_cpu"
                imageTag: ":12.2.1.4-jdk8-ol8"         
ocpdcrsm:
    isEnabled: false
    configEnv:
        useT3s: false
        isInboundOauthEnabled: false
        httpClients: []
    secretValue:
        httpClients: []
ocbc:
    bc:
        isEnabled: true
        configEnv:
            isOPSS: false
            isLDAPEnabled: false
        deployment:
            fmw:
                imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
                imageName: "middleware/fmw-infrastructure_cpu"
                imageTag: ":12.2.1.4-jdk8-ol8"
    bcws:
        isEnabled: true
        configEnv:
            isOPSS: false
            isLDAPEnabled: false
        deployment:
            fmw:
                imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
                imageName: "middleware/fmw-infrastructure_cpu"
                imageTag: ":12.2.1.4-jdk8-ol8"          
ocboc:
    boc:
        isEnabled: false
        deployment:
            fmw:
                imageRepository: "iad.ocir.io/id6cgo1s3kqm/enablement/brm15/"
                imageName: "middleware/fmw-infrastructure_cpu"
                imageTag: ":12.2.1.4-jdk8-ol8"        
ocpcc:
    pcc:
        isEnabled: false
ocrsm:
    rsm:
        isEnabled: false 
        configEnv:
            securityEnabled: false
            hostName: 1.2.3.4
            baseURL: 1.2.3.4
            rsmCertificateFileName: keyStore.p12
        service:
            type: NodePort


logging:
    isEnabled: false 

