# Copyright (c) 2021 Oracle Corporation and/or its affiliates. All rights reserved.
imageRepository: "iad.ocir.io/idqji4proemh/brmcn-ps7/"
imagePullSecrets: "brm-registry"
uniPass: "QzFHMmIzdTQjIw=="

db:    
    host: dbvm.sub3b8b1321d.cluster1.oraclevcn.com
    port: 1521
    user: sys
    password: cGluREI5OSMjCg==
    serviceName: PINPDB.sub3b8b1321d.cluster1.oraclevcn.com
    sslMode: 'NO'
ocbrm:
    db:
        schemauser: pin
        schemapass: QzFHMmIzdTQjIw==
        schematablespace: pin00
        indextablespace: pinx00
        pipelineschemauser: pin
    cm:
        deployment:
            enable_publish: 1
    eai_js:
        deployment:
            eaiConfigFile: payloadconfig_ece_sync.xml
    storage_class:
        create: false
        name: rook-cephfs
    virtual_time:
        enabled: true
    batchpipe:
        isEnabled: false

ocpdc:
     configEnv:
         rcuPrefix: rcupdc1
         pdcSchemaUserName: pdc
         crossRefSchemaUserName: xref
         pdcAdminUser: pdcuser
         transformation:
             supportECE: true
             isClearBRMSeedData: false 
             upgrade: false
         syncPDC:
             upgradeFromPS2: false
     service:
         type: "ClusterIP"
     wop:
         addOpssSecret: true
         opssWalletSecretName: pdc-domain-opss-wallet-secret1
ocbc:
    bc:
        configEnv:
            ldapSkip: true
            isOPSS: false
    bcws:
        configEnv:
            ldapSkip: true
            isOPSS: false
ocboc:
    boc:
        isEnabled: false
ocpcc:
    pcc:
        isEnabled: false
ocrsm:
    rsm:
        isEnabled: false

logging:
    isEnabled: false 

