apiVersion: v1
kind: Pod
metadata:
  name: groovy
spec:
  containers:
  - name: groovy
    image: groovy:latest
    stdin: true
    tty: true
    volumeMounts:
      - name: groovy-volume
        mountPath: /run # mount point in our container
  volumes:
    - name: groovy-volume
      persistentVolumeClaim:
        claimName: groovy-volume-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: groovy-volume-claim
spec:
  storageClassName: "rook-cephfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
